#Python program to find square root of any number...

num = int(input("Enter the number:"))       #Enter the number as per your choice...
sq_root = (num**0.5)                        #formula...
print("The square root is:",sq_root)